driver:
  name: hyperv
  parent_vhd_folder: C:\src\vm\
  parent_vhd_name: win2017u.vhdx
  # boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  # iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  # ip_address: 192.168.11.123
  # subnet: 255.255.255.0
  # gateway: 192.168.11.1
  # dns_servers: ['8.8.8.8']

transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      #configuration_mode_frequency_mins: 30
      #debug_mode: none
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    #modules_path: .
    #configuration_data_variable: configData
    #modules_from_gallery:
    # - xPSDesiredStateConfiguration
    # - PackageManagementProviderResource

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: win2016u_WMF5
    # os_type: windows
    # shell: powershell
    # transport:
    #   name: winrm
    # driver:
    #   parent_vhd: C:\src\hyperv\WIN2012R2\WIN2012r2_WMF5.vhd
    # provisioner:
    #   dsc_local_configuration_manager_version: wmf5

suites:
  - name: default