driver:
  name: hyperv
  parent_vhd_folder: C:\src\vm\
  parent_vhd_name: win2017u.vhdx
  memory_startup_bytes: 1073741824
  vm_switch: NAT

transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    modules_path: modules

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: win2016u_WMF5

suites:
  - name: default